### ISSUE TITLE
hcidump permission

### ISSUE THREAD

**Issue by ulrichard** [travisgoodspeed/pyspot#1]
As I received my ubuntu phone recently, your code became very handy.
The most important part for me is how to start tracking mode.
So I wanted to find out the verb myself, as the globalstar support people couldn't tell me.
But this is what I get:

$ adb shell hcidump -X | tee spotlog.txt
HCI sniffer - Bluetooth packet analyzer ver 2.0
Can't access device: Permission denied

How can I adjust the necessary permissions?

**Comment by travisgoodspeed** [comment]
Howdy!

You probably need to root the phone, running hcidump under a root shell.

Closing the issue as unrelated to the code, but I wish you the best. 

Cheers from Brooklyn,
-Travis
